// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides smart filter suggestions based on the user's search query for Magic: The Gathering cards.
 *
 * - `getSmartFilterSuggestions` - A function that takes a search query and returns suggested filters.
 * - `SmartFilterSuggestionsInput` - The input type for the `getSmartFilterSuggestions` function.
 * - `SmartFilterSuggestionsOutput` - The return type for the `getSmartFilterSuggestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SmartFilterSuggestionsInputSchema = z.object({
  query: z.string().describe('The user search query for Magic: The Gathering cards.'),
});
export type SmartFilterSuggestionsInput = z.infer<typeof SmartFilterSuggestionsInputSchema>;

const SmartFilterSuggestionsOutputSchema = z.object({
  suggestedFilters: z
    .array(z.string())
    .describe(
      'A list of suggested filters based on the search query.  Example filters include: Condition, Language, Price, Color, Edition, Cost of Mana.'
    ),
});
export type SmartFilterSuggestionsOutput = z.infer<typeof SmartFilterSuggestionsOutputSchema>;

const smartFilterSuggestionsPrompt = ai.definePrompt({
  name: 'smartFilterSuggestionsPrompt',
  input: {schema: SmartFilterSuggestionsInputSchema},
  output: {schema: SmartFilterSuggestionsOutputSchema},
  prompt: `You are an expert Magic: The Gathering card search assistant.  Based on the user's query, suggest the most relevant filters to narrow down the search.  Only suggest from the following list of filters: Condition, Language, Price, Color, Edition, Cost of Mana. If the query does not clearly indicate a filter, provide an empty array.

User Query: {{{query}}}

Here are a few examples:

* If the query is "blue cards", the suggested filters should be ["Color"].
* If the query is "cheap cards", the suggested filters should be ["Price"].
* If the query is "cards in Spanish", the suggested filters should be ["Language"].
* If the query is "mint condition cards", the suggested filters should be ["Condition"].
* If the query is "cards from the latest set", the suggested filters should be ["Edition"].
* If the query is "cards that cost 3 mana", the suggested filters should be ["Cost of Mana"].
* If the query is "", the suggested filters should be [].

Suggest filters in JSON format:
`,
});

export const smartFilterSuggestionsFlow = ai.defineFlow(
  {
    name: 'smartFilterSuggestionsFlow',
    inputSchema: SmartFilterSuggestionsInputSchema,
    outputSchema: SmartFilterSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await smartFilterSuggestionsPrompt(input);
    return output!;
  }
);
